import type { Metadata } from "next";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "The terms governing your use of ClearContract, including disclaimers, payment, and liability.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-[#09090b]">
      <Navbar />
      <main className="flex-1 py-20 px-5">
        <article className="max-w-3xl mx-auto">
          <h1 className="font-display text-4xl md:text-5xl font-bold text-white tracking-tight mb-3">
            Terms of Service
          </h1>
          <p className="text-zinc-500 text-sm mb-12">Last updated: May 24, 2026</p>

          <div className="space-y-10 text-zinc-300 leading-relaxed">
            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-white">1. The service</h2>
              <p className="text-zinc-400">
                ClearContract is a web application that uses large language models to
                read contracts and produce plain-English summaries, risk flags, and
                rewrite suggestions. By accessing the service you agree to these terms.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-white">2. Not legal advice</h2>
              <p className="text-zinc-400">
                ClearContract is an informational tool. The output is generated by AI
                and is not a substitute for advice from a licensed attorney. We do not
                form an attorney-client relationship with you. For any consequential
                legal decision, consult a qualified lawyer in your jurisdiction.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-white">3. Your account</h2>
              <p className="text-zinc-400">
                You are responsible for maintaining the confidentiality of your account
                credentials and for any activity under your account. You must be at
                least 18 years old and able to enter binding contracts in your
                jurisdiction.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-white">4. Payment and refunds</h2>
              <p className="text-zinc-400">
                Paid plans are billed monthly through Stripe. Subscriptions renew
                automatically until canceled. You may cancel at any time through the
                billing portal and will retain access through the end of the paid
                period. We offer a 14-day money-back guarantee on first-time paid
                subscriptions, email{" "}
                <a
                  href="mailto:support@clrct.com"
                  className="text-zinc-200 hover:text-white"
                >
                  support@clrct.com
                </a>{" "}
                within 14 days of your first charge to request a refund.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-white">5. Acceptable use</h2>
              <p className="text-zinc-400">You agree not to:</p>
              <ul className="list-disc pl-6 space-y-2 text-zinc-400">
                <li>Submit content you don&apos;t have the right to share.</li>
                <li>
                  Attempt to reverse-engineer, scrape, or overload the service or its
                  underlying providers.
                </li>
                <li>
                  Use the service to generate unlawful, harmful, deceptive, or
                  discriminatory output.
                </li>
                <li>
                  Resell, sublicense, or expose the service as a competing API without a
                  written commercial agreement.
                </li>
              </ul>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-white">6. Intellectual property</h2>
              <p className="text-zinc-400">
                You retain all rights to the contracts and content you submit. We
                retain all rights to the ClearContract software, design, branding, and
                aggregated, de-identified usage statistics. You grant us a limited
                license to process your input solely to deliver the service.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-white">7. Disclaimer of warranties</h2>
              <p className="text-zinc-400">
                The service is provided &quot;as is&quot; and &quot;as available&quot;,
                without warranties of any kind, express or implied. We do not guarantee
                that the output will be accurate, complete, or fit for any particular
                purpose.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-white">8. Limitation of liability</h2>
              <p className="text-zinc-400">
                To the maximum extent permitted by law, our total liability arising out
                of or relating to the service is limited to the greater of (a) the
                amount you paid us in the twelve months preceding the claim, or (b) one
                hundred U.S. dollars (USD $100). We are not liable for indirect,
                incidental, consequential, or punitive damages.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-white">9. Termination</h2>
              <p className="text-zinc-400">
                You may stop using the service at any time. We may suspend or terminate
                your account if you violate these terms or if continued service becomes
                impractical. On termination, your right to use the service ends; the
                sections that should survive termination by their nature (IP, liability,
                governing law) will continue to apply.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-white">10. Governing law</h2>
              <p className="text-zinc-400">
                These terms are governed by the laws of the State of Delaware, USA,
                without regard to conflict-of-laws principles. Any dispute will be
                resolved in the state or federal courts located in Delaware.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-white">11. Changes</h2>
              <p className="text-zinc-400">
                We may update these terms from time to time. Material changes will be
                announced on this page with an updated &quot;Last updated&quot; date.
                Continued use after changes constitutes acceptance.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-white">12. Contact</h2>
              <p className="text-zinc-400">
                Questions about these terms? Email{" "}
                <a
                  href="mailto:support@clrct.com"
                  className="text-zinc-200 hover:text-white"
                >
                  support@clrct.com
                </a>
                .
              </p>
            </section>
          </div>
        </article>
      </main>
      <Footer />
    </div>
  );
}
